name: Rebase Upstream
on:
  schedule:
  - cron: "42 8 * * 5"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 10
        token: ${{ secrets.GH_PAT }}
    - uses: imba-tjd/rebase-upstream-action@master
      with:
        upstream: EhViewer-NekoInverter/EhViewer
        branch: master
